import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './Header';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Meme Feed',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  username 
}: {
  children: React.ReactNode;
  username: string;
}) {
  return (
    <html lang="en">
			<body className={inter.className}>
        <Header username={username} />
				{children}
			</body>
		</html>
  )
}
