import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from "next/link"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
			<body className={inter.className}>
				<header>
					<Link href = "/"><img src = {"/assets/images/logo.png"} /></Link>
          <h2 className="header--title">Meme Generator</h2>
					<nav>
						<ul>
							<li><Link href = "/">HOME</Link></li>
						</ul>
					</nav>
				</header>
				{children}
			</body>
		</html>
  )
}
