# Generated by Django 4.2.3 on 2023-10-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meme_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('meme_image', models.ImageField(blank=True, default='../media/users/user_avtar.webp', null=True, upload_to='memes/')),
            ],
        ),
    ]
